### ISSUE TITLE
Export each book clippings to its own files

### ISSUE THREAD

**Issue by gunar** [baniol/kindle-my-clippings#5]
Thanks for `kindle-my-clippings`. It's a perfect fit for my needs.

It'd be cool to do something like `kindle-my-clippings --export-all` and have it create files as `1 - state-machine.txt`, `2- Of leisure.txt`...

I could provide a PR. Are you interested?

Thank you!

**Comment by baniol** [comment]
Glad you've found it useful. 
Why not adding the feature - just send me a PR.
Thanks.

**Comment by gunar** [comment]
Yo @baniol.

1. I've solve my issue. Actually, there weren't that many books I wanted to export so it was fine doing by hand.
2. I don't think many people would need this.

So I'm closing this now.

Thanks again!!
